<?php
declare(strict_types=1);
namespace Two13Tec\FlowShellCompletion\Command;

/*
 * This file is part of the Two13Tec.FlowShellCompletion package.
 *
 * (c) Two13Tec
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\Annotations as Flow;
use Neos\Flow\Cli\Command as FlowCommand;
use Neos\Flow\Cli\CommandController;
use Neos\Flow\Cli\CommandManager;

/**
 * Shell completion generation for Flow commands
 *
 * @Flow\Scope("singleton")
 */
class CompletionCommandController extends CommandController
{
    /**
     * @Flow\Inject
     * @var CommandManager
     */
    protected $commandManager;

    /**
     * Generate shell completion script
     *
     * This command generates shell completion scripts for Flow commands.
     *
     * Usage examples:
     *
     *   # Generate zsh completion
     *   ./flow completion:generate --shell=zsh
     *
     * @param string $shell Shell type: zsh
     * @return void
     */
    public function generateCommand(string $shell = 'zsh'): void
    {
        $shell = strtolower($shell);

        if ($shell !== 'zsh') {
            $this->outputLine('<error>Unsupported shell: %s</error>', [$shell]);
            $this->outputLine('Supported shells: zsh');
            $this->quit(1);
        }

        $this->output->output($this->generateZshCompletion());
    }

    /**
     * Install shell completion for the current user
     *
     * This command installs shell completion for Flow commands in the current
     * user's shell configuration. It automatically detects your shell and installs
     * the appropriate completion script.
     *
     * Supported shells: zsh
     *
     * @param string|null $shell Force specific shell (zsh), auto-detect if not specified
     * @return void
     */
    public function installCommand(?string $shell = null): void
    {
        // Auto-detect shell if not specified
        if ($shell === null) {
            $shell = basename(getenv('SHELL') ?: 'zsh');
        }

        $shell = strtolower($shell);

        if ($shell !== 'zsh') {
            $this->outputLine('<error>Unsupported shell: %s</error>', [$shell]);
            $this->outputLine('Supported shells: zsh');
            $this->quit(1);
        }

        $this->installZsh();
    }

    /**
     * Generate zsh completion script
     */
    protected function generateZshCompletion(): string
    {
        $commands = $this->getCommandCompletionEntries();

        $completionScript = <<<'ZSH'
# Neos Flow zsh completion
# Generated by Two13Tec.FlowShellCompletion

_flow() {
    local -a commands
    local line state

    _arguments -C \
        '1: :->command' \
        '*::arg:->args'

    case $state in
        command)
            commands=(

ZSH;

        foreach ($commands as $command) {
            $identifier = $this->escapeIdentifierForZsh($command['identifier']);
            $description = $this->escapeDescriptionForZsh($command['detailedDescription']);
            $completionScript .= sprintf("                '%s:%s'\n", $identifier, $description);
        }

        $completionScript .= <<<'ZSH'
            )
            _describe 'flow command' commands
            ;;
        args)
            case $line[1] in

ZSH;

        foreach ($commands as $command) {
            $completionScript .= sprintf(
                "                %s)\n                    %s\n                    ;;\n",
                $command['identifier'],
                $command['handler']
            );
        }

        $completionScript .= <<<'ZSH'
                *)
                    ;;
            esac
            ;;
    esac
}

compdef _flow flow
compdef _flow ./flow

ZSH;

        foreach ($commands as $command) {
            $completionScript .= $this->renderZshHandler($command);
        }

        return $completionScript;
    }

    /**
     * Render the handler function for a specific Flow command
     *
     * @param array{handler: string, arguments: array<int, array{dashedName: string, description: string, label: string, acceptsValue: bool}>} $command
     */
    protected function renderZshHandler(array $command): string
    {
        $optionSpecs = $this->buildZshOptionSpecs($command['arguments']);
        $lines = [];
        $lines[] = sprintf('%s()', $command['handler']);
        $lines[] = '{';
        $lines[] = '    _arguments -s \\';

        $lastIndex = count($optionSpecs) - 1;
        foreach ($optionSpecs as $index => $spec) {
            $continuation = $index === $lastIndex ? '' : ' \\';
            $lines[] = sprintf('        %s%s', $spec, $continuation);
        }

        $lines[] = '}';
        $lines[] = '';

        return implode(PHP_EOL, $lines);
    }

    /**
     * Build the `_arguments` specification for a command
     *
     * @param array<int, array{dashedName: string, description: string, label: string, acceptsValue: bool}> $arguments
     * @return array<int, string>
     */
    protected function buildZshOptionSpecs(array $arguments): array
    {
        $specs = [];
        foreach ($arguments as $argument) {
            $specs[] = $this->formatZshOptionSpec($argument);
        }
        $specs[] = "{-h,--help}'[Display help for this command]'";

        return $specs;
    }

    /**
     * Format a single option specification for `_arguments`
     *
     * @param array{dashedName: string, description: string, label: string, acceptsValue: bool} $argument
     */
    protected function formatZshOptionSpec(array $argument): string
    {
        $description = $this->escapeDescriptionForZsh($argument['description']);

        if ($argument['acceptsValue']) {
            return sprintf("'%s[%s]:%s:'", $argument['dashedName'], $description, $argument['label']);
        }

        return sprintf("'%s[%s]'", $argument['dashedName'], $description);
    }


    /**
     * Build completion entries with shortest identifiers, descriptions, and option metadata
     *
     * @return array<int, array{identifier: string, shortDescription: string, detailedDescription: string, handler: string, arguments: array<int, array{dashedName: string, description: string, label: string, acceptsValue: bool}>}>
     */
    protected function getCommandCompletionEntries(): array
    {
        $entries = [];
        foreach ($this->commandManager->getAvailableCommands() as $command) {
            $identifier = $this->commandManager->getShortestIdentifierForCommand($command);
            $shortDescription = trim($command->getShortDescription());
            if ($shortDescription === '') {
                $shortDescription = '<no description available>';
            }
            $detailedDescription = $shortDescription;
            $longDescription = trim($command->getDescription());
            if ($longDescription !== '') {
                $detailedDescription .= "\n" . $longDescription;
            }

            $entries[] = [
                'identifier' => $identifier,
                'shortDescription' => $shortDescription,
                'detailedDescription' => $detailedDescription,
                'handler' => $this->buildHandlerName($identifier),
                'arguments' => $this->buildCommandArguments($command),
            ];
        }

        usort($entries, static function (array $left, array $right): int {
            return strcmp($left['identifier'], $right['identifier']);
        });

        return $entries;
    }

    /**
     * Build the argument metadata for the given command
     *
     * @return array<int, array{dashedName: string, description: string, label: string, acceptsValue: bool}>
     */
    protected function buildCommandArguments(FlowCommand $command): array
    {
        if (!$command->hasArguments()) {
            return [];
        }

        $arguments = [];
        $parameters = $this->commandManager->getCommandMethodParameters(
            $command->getControllerClassName(),
            $command->getControllerCommandName() . 'Command'
        );

        foreach ($command->getArgumentDefinitions() as $argumentDefinition) {
            $name = $argumentDefinition->getName();
            $type = $parameters[$name]['type'] ?? null;

            $arguments[] = [
                'dashedName' => $argumentDefinition->getDashedName(),
                'description' => $argumentDefinition->getDescription(),
                'label' => strtolower($name),
                'acceptsValue' => $this->argumentExpectsValue($type),
            ];
        }

        return $arguments;
    }

    /**
     * Create a deterministic handler name for the zsh functions
     */
    protected function buildHandlerName(string $identifier): string
    {
        $sanitized = preg_replace('/[^A-Za-z0-9]+/', '_', $identifier);
        $sanitized = trim((string)$sanitized, '_');
        if ($sanitized === '') {
            $sanitized = 'command';
        }

        return '_flow_' . $sanitized;
    }

    /**
     * Determine whether an option expects a value based on its parameter type
     */
    protected function argumentExpectsValue(?string $type): bool
    {
        if ($type === null) {
            return true;
        }

        $type = strtolower(trim($type));
        $type = ltrim($type, '?');

        if (str_contains($type, '|')) {
            foreach (explode('|', $type) as $fragment) {
                $normalized = ltrim(strtolower(trim($fragment)), '?');
                if ($normalized !== 'bool' && $normalized !== 'boolean') {
                    return true;
                }
            }

            return false;
        }

        return $type !== 'bool' && $type !== 'boolean';
    }

    /**
     * Escape identifier for zsh completion entries
     */
    protected function escapeIdentifierForZsh(string $identifier): string
    {
        $identifier = str_replace('\\', '\\\\', $identifier);
        $identifier = str_replace(':', '\:', $identifier);
        return str_replace("'", "\\'", $identifier);
    }

    /**
     * Escape description for zsh completion entries (supports multiline output)
     */
    protected function escapeDescriptionForZsh(string $description): string
    {
        $normalized = str_replace(["\r\n", "\n", "\r"], ' ', $description);

        $search = ["'", '"', '\\', '[', ']', ':'];
        $replace = ['"', '\\"', '\\\\', '\\[', '\\]', '\\:'];

        return str_replace($search, $replace, $normalized);
    }


    /**
     * Install zsh completion
     *
     * @return void
     */
    protected function installZsh(): void
    {
        $projectRoot = FLOW_PATH_ROOT;
        $completionFile = $projectRoot . 'flow-completion.zsh';

        // Generate and write completion script
        file_put_contents($completionFile, $this->generateZshCompletion());
        $this->outputLine('→ Created zsh completion script: %s', [$completionFile]);

        // Check if already in .zshrc
        $zshrc = getenv('HOME') . '/.zshrc';
        $sourceLine = sprintf('source "%s"', $completionFile);

        if (file_exists($zshrc)) {
            $zshrcContent = file_get_contents($zshrc);
            if (strpos($zshrcContent, $completionFile) === false) {
                file_put_contents(
                    $zshrc,
                    PHP_EOL . '# Neos Flow completion' . PHP_EOL . $sourceLine . PHP_EOL,
                    FILE_APPEND
                );
                $this->outputLine('✓ Added source line to ~/.zshrc');
                $this->outputLine('');
                $this->outputLine('<info>Run "source ~/.zshrc" or restart your shell to activate completion.</info>');
            } else {
                $this->outputLine('<info>i Completion already configured in ~/.zshrc</info>');
            }
        } else {
            $this->outputLine('<comment>! ~/.zshrc not found. Add this line manually:</comment>');
            $this->outputLine('  ' . $sourceLine);
        }
    }

}
