<?php
declare(strict_types=1);
namespace Two13Tec\FlowShellCompletion\Command;

/*
 * This file is part of the Two13Tec.FlowShellCompletion package.
 *
 * (c) Two13Tec
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\Annotations as Flow;
use Neos\Flow\Cli\CommandController;
use Neos\Flow\Cli\CommandManager;

/**
 * Shell completion generation for Flow commands
 *
 * @Flow\Scope("singleton")
 */
class CompletionCommandController extends CommandController
{
    /**
     * @Flow\Inject
     * @var CommandManager
     */
    protected $commandManager;

    /**
     * Generate shell completion script
     *
     * This command generates shell completion scripts for Flow commands.
     *
     * Usage examples:
     *
     *   # Generate zsh completion
     *   ./flow completion:generate --shell=zsh
     *
     *   # Generate fish completion
     *   ./flow completion:generate --shell=fish
     *
     *   # Generate nix home-manager module
     *   ./flow completion:generate --shell=nix
     *
     * @param string $shell Shell type: zsh, fish, or nix
     * @return void
     */
    public function generateCommand(string $shell = 'zsh'): void
    {
        $shell = strtolower($shell);

        switch ($shell) {
            case 'zsh':
                $this->output->output($this->generateZshCompletion());
                break;
            case 'fish':
                $this->output->output($this->generateFishCompletion());
                break;
            case 'nix':
                $this->output->output($this->generateNixModule());
                break;
            default:
                $this->outputLine('<error>Unsupported shell: %s</error>', [$shell]);
                $this->outputLine('Supported shells: zsh, fish, nix');
                $this->quit(1);
        }
    }

    /**
     * Install shell completion for the current user
     *
     * This command installs shell completion for Flow commands in the current
     * user's shell configuration. It automatically detects your shell and installs
     * the appropriate completion script.
     *
     * Supported shells: zsh, fish
     *
     * @param string|null $shell Force specific shell (zsh or fish), auto-detect if not specified
     * @return void
     */
    public function installCommand(?string $shell = null): void
    {
        // Auto-detect shell if not specified
        if ($shell === null) {
            $shell = basename(getenv('SHELL') ?: 'zsh');
        }

        $shell = strtolower($shell);

        switch ($shell) {
            case 'zsh':
                $this->installZsh();
                break;
            case 'fish':
                $this->installFish();
                break;
            default:
                $this->outputLine('<error>Unsupported shell: %s</error>', [$shell]);
                $this->outputLine('Supported shells: zsh, fish');
                $this->outputLine('For nix/home-manager, use: ./flow completion:generate --shell=nix');
                $this->quit(1);
        }
    }

    /**
     * Generate zsh completion script
     *
     * @return string
     */
    protected function generateZshCompletion(): string
    {
        $commands = $this->getCommandCompletionEntries();

        $completionScript = <<<'ZSH'
# Neos Flow zsh completion
# Generated by Two13Tec.FlowShellCompletion

_flow() {
    local -a commands
    local state

    _arguments -C \
        '1: :->command' \
        '*::arg:->args'

    case $state in
        command)
            commands=(

ZSH;

        foreach ($commands as $command) {
            $identifier = $this->escapeIdentifierForZsh($command['identifier']);
            $description = $this->escapeDescriptionForZsh($command['detailedDescription']);
            $completionScript .= sprintf("                '%s:%s'\n", $identifier, $description);
        }

        $completionScript .= <<<'ZSH'
            )
            _describe 'flow command' commands
            ;;
        args)
            # Future: Add argument/option completion based on command
            ;;
    esac
}

compdef _flow flow
compdef _flow ./flow
ZSH;

        return $completionScript;
    }

    /**
     * Generate fish completion script
     *
     * @return string
     */
    protected function generateFishCompletion(): string
    {
        $commands = $this->getCommandCompletionEntries();

        $completionScript = "# Neos Flow fish completion\n";
        $completionScript .= "# Generated by Two13Tec.FlowShellCompletion\n\n";
        $completionScript .= "# Remove default file completions\n";
        $completionScript .= "complete -c flow -e\n\n";

        foreach ($commands as $command) {
            $identifier = $this->escapeForSingleQuotes($command['identifier']);
            $shortDescription = $this->escapeForSingleQuotes($command['shortDescription']);
            // Escape quotes for fish
            $completionScript .= sprintf(
                "complete -c flow -f -n '__fish_use_subcommand' -a '%s' -d '%s'\n",
                $identifier,
                $shortDescription
            );
        }

        return $completionScript;
    }

    /**
     * Generate nix home-manager module
     *
     * @return string
     */
    protected function generateNixModule(): string
    {
        $projectRoot = FLOW_PATH_ROOT;
        $absoluteFlowPath = $projectRoot . 'flow';
        $commands = $this->getCommandCompletionEntries();

        $nixModule = <<<NIX
# Neos Flow shell completion for nix/home-manager
# Generated by Two13Tec.FlowShellCompletion
#
# Add this to your home-manager configuration:
#
#   imports = [ ./flow-completion.nix ];
#
# Or inline in your home.nix:
#
#   programs.zsh.initExtra = ''
#     source <(command cat $projectRoot/flow-completion.zsh)
#   '';

{ config, pkgs, lib, ... }:

{
  programs.zsh.initExtra = lib.mkIf config.programs.zsh.enable ''
    # Neos Flow completion
    if [ -f "$absoluteFlowPath" ]; then
      _flow_completion() {
        local -a commands
        commands=(

NIX;

        foreach ($commands as $command) {
            $identifier = $this->escapeIdentifierForZsh($command['identifier']);
            $shortDescription = $this->escapeForSingleQuotes($command['shortDescription']);
            $nixModule .= sprintf("          '%s:%s'\n", $identifier, $shortDescription);
        }

        $nixModule .= <<<NIX
        )
        _describe 'flow command' commands
      }
      compdef _flow_completion flow
    fi
  '';

  programs.fish.shellInit = lib.mkIf config.programs.fish.enable ''
    # Neos Flow completion
    if test -f "$absoluteFlowPath"

NIX;

        foreach ($commands as $command) {
            $identifier = $this->escapeForSingleQuotes($command['identifier']);
            $shortDescription = $this->escapeForSingleQuotes($command['shortDescription']);
            $nixModule .= sprintf(
                "      complete -c flow -f -n '__fish_use_subcommand' -a '%s' -d '%s'\n",
                $identifier,
                $shortDescription
            );
        }

        $nixModule .= <<<NIX
    end
  '';
}

NIX;

        return $nixModule;
    }

    /**
     * Build completion entries with shortest identifiers and descriptions
     *
     * @return array<int, array{identifier: string, shortDescription: string, detailedDescription: string}>
     */
    protected function getCommandCompletionEntries(): array
    {
        $entries = [];
        foreach ($this->commandManager->getAvailableCommands() as $command) {
            $identifier = $this->commandManager->getShortestIdentifierForCommand($command);
            $shortDescription = trim($command->getShortDescription());
            if ($shortDescription === '') {
                $shortDescription = '<no description available>';
            }
            $detailedDescription = $shortDescription;
            $longDescription = trim($command->getDescription());
            if ($longDescription !== '') {
                $detailedDescription .= "\n" . $longDescription;
            }
            $entries[] = [
                'identifier' => $identifier,
                'shortDescription' => $shortDescription,
                'detailedDescription' => $detailedDescription,
            ];
        }

        usort($entries, static function (array $left, array $right): int {
            return strcmp($left['identifier'], $right['identifier']);
        });

        return $entries;
    }

    /**
     * Escape identifier for zsh completion entries
     */
    protected function escapeIdentifierForZsh(string $identifier): string
    {
        $identifier = str_replace('\\', '\\\\', $identifier);
        $identifier = str_replace(':', '\:', $identifier);
        return str_replace("'", "\\'", $identifier);
    }

    /**
     * Escape description for zsh completion entries (supports multiline output)
     */
    protected function escapeDescriptionForZsh(string $description): string
    {
        $normalized = str_replace("\n", " ", $description);
        $escaped = str_replace("'", "\"", $normalized);
        return $escaped;
    }

    /**
     * Escape strings that will be wrapped in single quotes
     */
    protected function escapeForSingleQuotes(string $value): string
    {
        return str_replace(["\\", "'"], ["\\\\", "\\'"], $value);
    }


    /**
     * Install zsh completion
     *
     * @return void
     */
    protected function installZsh(): void
    {
        $projectRoot = FLOW_PATH_ROOT;
        $completionFile = $projectRoot . 'flow-completion.zsh';

        // Generate and write completion script
        file_put_contents($completionFile, $this->generateZshCompletion());
        $this->outputLine('→ Created zsh completion script: %s', [$completionFile]);

        // Check if already in .zshrc
        $zshrc = getenv('HOME') . '/.zshrc';
        $sourceLine = sprintf('source "%s"', $completionFile);

        if (file_exists($zshrc)) {
            $zshrcContent = file_get_contents($zshrc);
            if (strpos($zshrcContent, $completionFile) === false) {
                file_put_contents(
                    $zshrc,
                    PHP_EOL . '# Neos Flow completion' . PHP_EOL . $sourceLine . PHP_EOL,
                    FILE_APPEND
                );
                $this->outputLine('✓ Added source line to ~/.zshrc');
                $this->outputLine('');
                $this->outputLine('<info>Run "source ~/.zshrc" or restart your shell to activate completion.</info>');
            } else {
                $this->outputLine('<info>i Completion already configured in ~/.zshrc</info>');
            }
        } else {
            $this->outputLine('<comment>! ~/.zshrc not found. Add this line manually:</comment>');
            $this->outputLine('  ' . $sourceLine);
        }
    }

    /**
     * Install fish completion
     *
     * @return void
     */
    protected function installFish(): void
    {
        $configDir = getenv('HOME') . '/.config/fish';
        $completionsDir = $configDir . '/completions';

        if (!is_dir($completionsDir)) {
            if (!is_dir($configDir)) {
                $this->outputLine('<error>Fish config directory not found: %s</error>', [$configDir]);
                $this->outputLine('Please install fish shell first.');
                $this->quit(1);
            }
            mkdir($completionsDir, 0755, true);
            $this->outputLine('→ Created fish completions directory: %s', [$completionsDir]);
        }

        $completionFile = $completionsDir . '/flow.fish';
        file_put_contents($completionFile, $this->generateFishCompletion());
        $this->outputLine('✓ Installed fish completion: %s', [$completionFile]);
        $this->outputLine('');
        $this->outputLine('<info>Fish will automatically load completions on next shell start.</info>');
    }
}
